// ─── Fantasy Genre Pack ──────────────────────────────────────────────────────
// The canonical fantasy content for Legendary. This file is the SINGLE source
// of truth for fantasy classes/races/starting gear; both the character-creation
// UI and the server-side character bootstrap read from here. Touching numbers
// here changes the game.
//
// NB: behaviour must remain identical to the pre-genre-system version. If you
// edit a number, make sure you intend to.

import type { GenreDefinition, ClassDef, RaceDef } from "./types";

const COMMON_INVENTORY = [
  { name: "Rations (3 days)", type: "consumable", qty: 1, properties: {} },
  { name: "Torch", type: "tool", qty: 3, properties: {} },
  { name: "Coin Pouch (10gp)", type: "treasure", qty: 1, properties: { value: 10 } },
];

const BASE_STATS = { might: 10, agility: 10, endurance: 10, intellect: 10, will: 10, presence: 10 };

const CLASSES: ClassDef[] = [
  {
    id: "fighter",
    name: "Fighter",
    iconName: "Sword",
    color: "text-red-400",
    description: "Masters of martial combat. Strong, resilient, and capable of extraordinary physical feats.",
    stats: "Might 14, Endurance 12",
    abilities: "Second Wind, Action Surge",
    gear: "Longsword, Chain Mail, Shield",
    baseHp: 12,
    baseMp: 0,
    baseStats: { ...BASE_STATS, might: 14, endurance: 12 },
    startingInventory: [
      ...COMMON_INVENTORY,
      { name: "Longsword", type: "weapon", qty: 1, rarity: "common", equipped: true, properties: { damage: "1d8", bonus: 2 } },
      { name: "Chain Mail", type: "armor", qty: 1, rarity: "common", equipped: true, properties: { ac: 14, slot: "body" } },
      { name: "Shield", type: "armor", qty: 1, rarity: "common", equipped: true, properties: { ac_bonus: 2 } },
    ],
    startingAbilities: [
      { id: "second_wind", name: "Second Wind", description: "Regain 1d10+level HP as a bonus action (recharges after a rest)", usesMax: 1, usesLeft: 1, recharge: "per-rest" },
      { id: "action_surge", name: "Action Surge", description: "Take an extra action on your turn (recharges after a rest)", usesMax: 1, usesLeft: 1, recharge: "per-rest" },
    ],
  },
  {
    id: "rogue",
    name: "Rogue",
    iconName: "Dices",
    color: "text-emerald-400",
    description: "Cunning and agile. Masters of stealth, subterfuge, and striking at the perfect moment.",
    stats: "Agility 14, Presence 12",
    abilities: "Sneak Attack, Cunning Action",
    gear: "Short Sword, Daggers, Thieves' Tools",
    baseHp: 8,
    baseMp: 0,
    baseStats: { ...BASE_STATS, agility: 14, presence: 12 },
    startingInventory: [
      ...COMMON_INVENTORY,
      { name: "Short Sword", type: "weapon", qty: 1, rarity: "common", equipped: true, properties: { damage: "1d6", bonus: 2 } },
      { name: "Daggers", type: "weapon", qty: 3, rarity: "common", properties: { damage: "1d4", thrown: true } },
      { name: "Leather Armor", type: "armor", qty: 1, rarity: "common", equipped: true, properties: { ac: 11, slot: "body" } },
      { name: "Thieves' Tools", type: "tool", qty: 1, properties: {} },
    ],
    startingAbilities: [
      { id: "sneak_attack", name: "Sneak Attack", description: "Deal 1d6 extra damage when you have advantage or an ally nearby", usesMax: -1, usesLeft: -1, recharge: "at-will" },
      { id: "cunning_action", name: "Cunning Action", description: "Dash, Disengage, or Hide as a bonus action", usesMax: -1, usesLeft: -1, recharge: "at-will" },
    ],
  },
  {
    id: "wizard",
    name: "Wizard",
    iconName: "ScrollText",
    color: "text-violet-400",
    description: "Scholars of arcane lore. Wield powerful spells and reshape reality through study and will.",
    stats: "Intellect 14, Will 12",
    abilities: "Arcane Blast, Mage Armor, Sleep",
    gear: "Arcane Staff, Spellbook, Focus Crystal",
    baseHp: 6,
    baseMp: 20,
    baseStats: { ...BASE_STATS, intellect: 14, will: 12 },
    startingInventory: [
      ...COMMON_INVENTORY,
      { name: "Arcane Staff", type: "weapon", qty: 1, rarity: "common", equipped: true, properties: { damage: "1d6" } },
      { name: "Spellbook", type: "tool", qty: 1, properties: {} },
      { name: "Robes", type: "armor", qty: 1, rarity: "common", equipped: true, properties: { ac: 10, slot: "body" } },
      { name: "Focus Crystal", type: "misc", qty: 1, properties: { focus: 3 } },
    ],
    startingAbilities: [
      { id: "arcane_blast", name: "Arcane Blast", description: "Ranged spell attack dealing 1d10 force damage", usesMax: -1, usesLeft: -1, recharge: "at-will" },
      { id: "mage_armor", name: "Mage Armor", description: "Set AC to 13+agility modifier for 8 hours (uses 1 Focus)", usesMax: -1, usesLeft: -1, recharge: "at-will" },
      { id: "sleep_spell", name: "Sleep", description: "Put creatures in a 20ft radius to sleep (uses 1 Focus). Affects up to 5d8 HP worth of creatures", usesMax: 2, usesLeft: 2, recharge: "per-rest" },
    ],
  },
  {
    id: "cleric",
    name: "Cleric",
    iconName: "Shield",
    color: "text-amber-400",
    description: "Divine conduits. Channel sacred power to heal allies, smite foes, and turn the tide of battle.",
    stats: "Will 14, Presence 12",
    abilities: "Sacred Flame, Healing Word, Divine Smite",
    gear: "Mace, Scale Mail, Holy Symbol",
    baseHp: 10,
    baseMp: 15,
    baseStats: { ...BASE_STATS, will: 14, presence: 12 },
    startingInventory: [
      ...COMMON_INVENTORY,
      { name: "Mace", type: "weapon", qty: 1, rarity: "common", equipped: true, properties: { damage: "1d6", bonus: 1 } },
      { name: "Scale Mail", type: "armor", qty: 1, rarity: "common", equipped: true, properties: { ac: 13, slot: "body" } },
      { name: "Holy Symbol", type: "misc", qty: 1, properties: {} },
      { name: "Prayer Beads", type: "misc", qty: 1, properties: { focus: 2 } },
    ],
    startingAbilities: [
      { id: "sacred_flame", name: "Sacred Flame", description: "Ranged spell attack dealing 1d8 radiant damage", usesMax: -1, usesLeft: -1, recharge: "at-will" },
      { id: "healing_word", name: "Healing Word", description: "Heal a creature for 1d4+will modifier HP (uses 1 Focus)", usesMax: -1, usesLeft: -1, recharge: "at-will" },
      { id: "divine_smite", name: "Divine Smite", description: "Add 2d8 radiant damage to a melee hit (uses 1 Focus)", usesMax: -1, usesLeft: -1, recharge: "at-will" },
    ],
  },
  {
    id: "ranger",
    name: "Ranger",
    iconName: "Target",
    color: "text-teal-400",
    description: "Hunters of the wild. Expert trackers who blend martial skill with nature magic to stalk their prey.",
    stats: "Agility 14, Endurance 12",
    abilities: "Hunter's Mark, Volley, Natural Explorer",
    gear: "Longbow, Short Sword, Studded Leather",
    baseHp: 10,
    baseMp: 8,
    baseStats: { ...BASE_STATS, agility: 14, endurance: 12 },
    startingInventory: [
      ...COMMON_INVENTORY,
      { name: "Longbow", type: "weapon", qty: 1, rarity: "common", equipped: true, properties: { damage: "1d8", range: 150 } },
      { name: "Arrows", type: "consumable", qty: 20, properties: {} },
      { name: "Short Sword", type: "weapon", qty: 1, rarity: "common", properties: { damage: "1d6", bonus: 1 } },
      { name: "Studded Leather Armor", type: "armor", qty: 1, rarity: "common", equipped: true, properties: { ac: 12, slot: "body" } },
      { name: "Herbalism Kit", type: "tool", qty: 1, properties: {} },
    ],
    startingAbilities: [
      { id: "hunters_mark", name: "Hunter's Mark", description: "Mark a creature as your quarry. Deal 1d6 extra damage against it and track it unerringly (concentration)", usesMax: -1, usesLeft: -1, recharge: "at-will" },
      { id: "volley", name: "Volley", description: "Fire a hail of arrows in a 10ft radius; each creature makes an Agility save (DC 13) or takes 1d8 damage", usesMax: 2, usesLeft: 2, recharge: "per-rest" },
      { id: "natural_explorer", name: "Natural Explorer", description: "Advantage on Endurance checks in wilderness, never lost outdoors, double rations foraged", usesMax: -1, usesLeft: -1, recharge: "at-will" },
    ],
  },
  {
    id: "paladin",
    name: "Paladin",
    iconName: "Star",
    color: "text-yellow-300",
    description: "Holy warriors bound by sacred oaths. Combine martial prowess with divine grace to protect the innocent.",
    stats: "Might 14, Will 12",
    abilities: "Lay on Hands, Divine Smite, Aura of Protection",
    gear: "Longsword, Half-Plate, Shield, Holy Symbol",
    baseHp: 10,
    baseMp: 8,
    baseStats: { ...BASE_STATS, might: 14, will: 12 },
    startingInventory: [
      ...COMMON_INVENTORY,
      { name: "Longsword", type: "weapon", qty: 1, rarity: "common", equipped: true, properties: { damage: "1d8", bonus: 2 } },
      { name: "Shield", type: "armor", qty: 1, rarity: "common", equipped: true, properties: { ac_bonus: 2 } },
      { name: "Half-Plate", type: "armor", qty: 1, rarity: "common", equipped: true, properties: { ac: 15, slot: "body" } },
      { name: "Holy Symbol", type: "misc", qty: 1, properties: { focus: 3 } },
      { name: "Healing Potion", type: "consumable", qty: 1, properties: { heal: "2d4+2" } },
    ],
    startingAbilities: [
      { id: "lay_on_hands", name: "Lay on Hands", description: "Touch a creature to restore up to 5 HP from a shared pool (pool refreshes after a rest)", usesMax: 5, usesLeft: 5, recharge: "per-rest" },
      { id: "paladin_divine_smite", name: "Divine Smite", description: "After hitting with a melee weapon, expend 1 Focus to deal an extra 2d8 radiant damage", usesMax: -1, usesLeft: -1, recharge: "at-will" },
      { id: "aura_of_protection", name: "Aura of Protection", description: "Allies within 10ft add your Will modifier to all saving throws", usesMax: -1, usesLeft: -1, recharge: "at-will" },
    ],
  },
  {
    id: "barbarian",
    name: "Barbarian",
    iconName: "Flame",
    color: "text-orange-400",
    description: "Primal warriors who tap into a furious rage. Fearsome and nigh-unstoppable on the battlefield.",
    stats: "Might 14, Endurance 14",
    abilities: "Rage, Reckless Attack, Danger Sense",
    gear: "Greataxe, Handaxe, Hide Armor",
    baseHp: 12,
    baseMp: 0,
    baseStats: { ...BASE_STATS, might: 14, endurance: 14 },
    startingInventory: [
      ...COMMON_INVENTORY,
      { name: "Greataxe", type: "weapon", qty: 1, rarity: "common", equipped: true, properties: { damage: "1d12", bonus: 2, two_handed: true } },
      { name: "Handaxe", type: "weapon", qty: 2, rarity: "common", properties: { damage: "1d6", thrown: true } },
      { name: "Hide Armor", type: "armor", qty: 1, rarity: "common", equipped: true, properties: { ac: 12, slot: "body" } },
      { name: "Hunting Trap", type: "tool", qty: 1, properties: {} },
    ],
    startingAbilities: [
      { id: "rage", name: "Rage", description: "Enter a furious rage for 1 minute: +2 damage on melee attacks, resistance to physical damage, advantage on Might checks (2 uses, recharges after a rest)", usesMax: 2, usesLeft: 2, recharge: "per-rest" },
      { id: "reckless_attack", name: "Reckless Attack", description: "Attack with advantage, but enemies also have advantage against you until your next turn", usesMax: -1, usesLeft: -1, recharge: "at-will" },
      { id: "danger_sense", name: "Danger Sense", description: "Advantage on Agility saving throws against effects you can see (traps, spells, hazards)", usesMax: -1, usesLeft: -1, recharge: "at-will" },
    ],
  },
  {
    id: "bard",
    name: "Bard",
    iconName: "Music",
    color: "text-rose-400",
    description: "Virtuosos of magic and charm. Inspire allies, confound enemies, and bend fate with song and story.",
    stats: "Presence 14, Will 12",
    abilities: "Bardic Inspiration, Cutting Words, Vicious Mockery",
    gear: "Rapier, Lute, Leather Armor, Component Pouch",
    baseHp: 8,
    baseMp: 15,
    baseStats: { ...BASE_STATS, presence: 14, will: 12 },
    startingInventory: [
      ...COMMON_INVENTORY,
      { name: "Rapier", type: "weapon", qty: 1, rarity: "common", equipped: true, properties: { damage: "1d8", bonus: 1, finesse: true } },
      { name: "Lute", type: "misc", qty: 1, properties: { focus: 3 } },
      { name: "Leather Armor", type: "armor", qty: 1, rarity: "common", equipped: true, properties: { ac: 11, slot: "body" } },
      { name: "Component Pouch", type: "misc", qty: 1, properties: {} },
      { name: "Disguise Kit", type: "tool", qty: 1, properties: {} },
    ],
    startingAbilities: [
      { id: "bardic_inspiration", name: "Bardic Inspiration", description: "Grant an ally a d6 they can add to any roll in the next 10 minutes (Presence modifier uses, recharges after a long rest)", usesMax: 3, usesLeft: 3, recharge: "per-day" },
      { id: "cutting_words", name: "Cutting Words", description: "Spend Bardic Inspiration to reduce an enemy's attack roll, damage roll, or ability check by 1d6", usesMax: -1, usesLeft: -1, recharge: "at-will" },
      { id: "vicious_mockery", name: "Vicious Mockery", description: "Psychic insult deals 1d4 damage and gives the target disadvantage on its next attack (Will save DC 13 to resist)", usesMax: -1, usesLeft: -1, recharge: "at-will" },
    ],
  },
];

const RACES: RaceDef[] = [
  { name: "Human",      description: "Adaptable and endlessly driven, humans spread across every corner of the world through ambition and will.",                      traits: "+1 to all stats · Bonus Proficiency · Extra Language",            bonuses: { might: 1, agility: 1, endurance: 1, intellect: 1, will: 1, presence: 1 } },
  { name: "Elf",        description: "Ancient and graceful, elves carry millennia of memory in their eyes and move like living poetry through any landscape.",       traits: "+2 Agility · Darkvision · Trance (4-hr rest) · Keen Senses",      bonuses: { agility: 2 } },
  { name: "Dwarf",      description: "Born of stone and tradition, dwarves are unyielding in battle and fiercely loyal to kin, clan, and craft.",                    traits: "+2 Endurance · Darkvision · Poison Resistance · Stone Sense",     bonuses: { endurance: 2 } },
  { name: "Halfling",   description: "Small in stature but boundless in courage, halflings carry an uncanny luck that bends fate to their favor.",                   traits: "+2 Agility · Lucky (reroll 1s) · Brave · Naturally Stealthy",     bonuses: { agility: 2 } },
  { name: "Half-Orc",   description: "Born between two worlds, half-orcs channel primal fury into devastating strength and shrug off blows that fell others.",       traits: "+2 Might · +1 Endurance · Relentless Endurance · Savage Attacks", bonuses: { might: 2, endurance: 1 } },
  { name: "Tiefling",   description: "Touched by infernal blood, tieflings bear the mark of the lower planes but forge their own destiny through will alone.",       traits: "+2 Presence · +1 Intellect · Darkvision · Hellish Rebuke · Fire Resistance", bonuses: { presence: 2, intellect: 1 } },
  { name: "Dragonborn", description: "Proud descendants of dragonkind who carry draconic power in their blood, unleashing elemental breath in battle.",              traits: "+2 Might · +1 Presence · Breath Weapon · Draconic Ancestry · Damage Resistance", bonuses: { might: 2, presence: 1 } },
  { name: "Gnome",      description: "Inventive and irrepressibly curious, gnomes approach every problem with a tinkerer's mind and a trickster's heart.",           traits: "+2 Intellect · Gnome Cunning (adv. mental saves) · Darkvision · Tinker",        bonuses: { intellect: 2 } },
  { name: "Aasimar",    description: "Blessed with celestial lineage, aasimar radiate an inner light and are called by divine forces to champion the innocent.",     traits: "+2 Will · +1 Presence · Healing Hands · Radiant Soul · Celestial Resistance",   bonuses: { will: 2, presence: 1 } },
  { name: "Tabaxi",     description: "Feline wanderers driven by insatiable curiosity, tabaxi move with preternatural speed and strike like an uncoiled spring.",    traits: "+2 Agility · +1 Presence · Cat's Claws · Feline Agility · Darkvision",          bonuses: { agility: 2, presence: 1 } },
  { name: "Genasi",     description: "Born of elemental fire and mortal blood, genasi blaze with inner heat that shapes their personality and powers alike.",        traits: "+2 Intellect · +1 Endurance · Fire Resistance · Reach to the Blaze · Darkvision", bonuses: { intellect: 2, endurance: 1 } },
  { name: "Firbolg",    description: "Gentle giants of the ancient forests, firbolgs commune with nature and prefer diplomacy — but are terrifying when roused.",    traits: "+2 Will · +1 Might · Detect Magic · Hidden Step · Powerful Build",              bonuses: { will: 2, might: 1 } },
];

export const FANTASY: GenreDefinition = {
  id: "fantasy",
  label: "Fantasy",
  tagline: "Swords, sorcery, and sworn destinies.",
  description: "The classic high-fantasy adventure — knights, mages, druids, and rogues in a world of dragons, dungeons, and ancient lore.",
  iconName: "Swords",
  comingSoon: false,
  classes: CLASSES,
  races: RACES,
  raceLabel: "Race",
  backgrounds: [
    "Soldier", "Scholar", "Criminal", "Acolyte", "Merchant", "Noble", "Outlander",
    "Sailor", "Folk Hero", "Hermit", "Charlatan", "Guild Artisan",
  ],
  personalityTraits: [
    "Brave", "Cunning", "Compassionate", "Ruthless", "Wise", "Reckless",
    "Honourable", "Ambitious", "Haunted", "Cheerful", "Stoic", "Pious",
    "Sarcastic", "Curious", "Loyal", "Mysterious",
  ],
  motivations: [
    "Vengeance", "Redemption", "Wealth", "Knowledge", "Fame", "Justice",
    "Protect loved ones", "Freedom", "Power", "Belonging", "Duty", "Survival",
  ],
  flaws: [
    "Crippling guilt", "Blind rage", "Cowardice at heart", "Greed",
    "Dark secret", "Reckless pride", "Betrayed a friend", "Addiction",
    "Owes a dangerous debt", "Fears death above all", "Cannot trust anyone", "Lost faith",
  ],
  names: [
    "Aldric", "Brynn", "Caelum", "Dara", "Elara", "Fenwick", "Gael", "Hestia",
    "Idris", "Jora", "Kael", "Lyra", "Morrigan", "Nyx", "Oren", "Petra",
    "Quill", "Rowan", "Sable", "Theron", "Umber", "Vesper", "Wren", "Xara",
    "Yara", "Zephyr", "Ashara", "Bram", "Cirdan", "Dahlia", "Eirik", "Freya",
    "Grimshaw", "Isolde", "Kaelen", "Liora", "Mazrek", "Niamh", "Ondra", "Ravenna",
  ],
  gmVoice: "You are running a high-fantasy tabletop RPG in the tradition of Dungeons & Dragons and classic sword-and-sorcery fiction. Lean into wonder, danger, magic, and mythic stakes.",
  portraitStyle: "Semi-realistic painterly digital art in the style of modern fantasy concept art and JRPG illustration. Soft diffused volumetric lighting with atmospheric haze, god-rays, and dramatic silhouettes. Rich tonal depth — warm amber/gold highlights against cool blue-grey shadows. Loose, textured brushwork that suggests detail without hard edges. Cinematic composition with depth-of-field blur. Luminous, ethereal atmosphere. High-detail environment but slightly soft and painterly, never photorealistic or cartoony. Moody and evocative. No text, no HUD, no UI overlays.",
};
